apiVersion: v1
kind: Service
metadata:
  name: sii-front-service
spec:
  selector:
    app: sii-front
  ports:
  - protocol: TCP
    port: 80 # Порт, который будет доступен извне кластера
    targetPort: 80 # Порт внутри контейнера
  type: NodePort # Для Minikube это лучший вариант
