name: CI/CD Pipeline

on:
  push:
    branches: [ main ] # Запускать при push в main
  pull_request:
    branches: [ main ] # Запускать при pull request в main
jobs:
  build-and-test:
    runs-on: ubuntu-latest # Среда выполнения
    steps:
    - name: Checkout code
      uses: actions/checkout@v3 # Скачать код проекта
    - name: Set up NodeJS # Пример для Python, адаптируйте под ваш язык
      uses: actions/setup-node@v4
      with:
        node-version: '22.x'
        cache: 'npm'
    - name: Install dependencies and test
      run: |
        npm ci
        npm run build --if-present # Пример зависимостей
        npm test # Запуск тестов
  docker-build-push:
    needs: build-and-test # Запускать после build-and-test
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        context: . # Путь к Dockerfile
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/sii_front:latest # ВАШ ОБРАЗ!
  deploy-to-vm:
    needs: docker-build-push # Запускать после docker-build-push
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Set up SSH Agent
      uses: webfactory/ssh-agent@v0.7.0
      with:
        ssh-private-key: ${{ secrets.DEPLOY_KEY }}
    - name: Add host key to known_hosts
      run: ssh-keyscan arsine.ru >> ~/.ssh/known_hosts # Убедиться, что IP ВМ известен
    - name: Deploy to server
      env:
        SSH_HOST: arsine.ru
        SSH_USER: zen
      run: |
        ssh ${{ env.SSH_HOST }} "
        docker stop sii_front || true && # Остановить старый контейнер, если есть
        docker rm sii_front || true && # Удалить старый контейнер
        docker pull ${{ secrets.DOCKERHUB_USERNAME }}/sii_front:latest && # Скачать новый образ
        docker run -d -p 8081:80 --name sii_front ${{ secrets.DOCKERHUB_USERNAME }}/sii_front:latest # Запустить новый контейнер
